const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
  page.on('pageerror', (e) => console.log('PAGE_ERR:', String(e).slice(0, 200)));
  await page.goto('http://localhost:7100/', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(4000);
  const card = page.locator('article[data-node-id="intent_executor"]').first();
  await card.dblclick({ timeout: 5000 }); await page.waitForTimeout(450);
  await card.dblclick({ timeout: 5000 }); await page.waitForTimeout(900);
  await page.locator('button:has-text("执行业务根")').first().click();
  await page.waitForTimeout(2500);
  const st = await page.evaluate(() => (document.querySelector('.runtime-inspector-surface') || {}).innerText.replace(/\n/g, ' '));
  console.log('EXEC:', JSON.stringify(st));
  await page.keyboard.press('Escape'); await page.waitForTimeout(700);
  const rt = page.locator('article[data-node-id="run_trace"]').first();
  await rt.dblclick({ timeout: 5000 }); await page.waitForTimeout(450);
  await rt.dblclick({ timeout: 5000 }); await page.waitForTimeout(900);
  const rows = await page.evaluate(() => [...document.querySelectorAll('.trace-row')].slice(0, 3).map((r) => r.innerText.replace(/\n/g, ' | ').slice(0, 220)));
  console.log('ROWS:', JSON.stringify(rows));
  await page.screenshot({ path: 'shots/73-trace-data.png' });
  await browser.close();
})().catch((e) => { console.error('FATAL', String(e).slice(0, 300)); process.exit(1); });
